micronaut:
  application:
    name: mdDataHawkeye
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/geodatadb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
---
jpa:
  default:
    packages-to-scan:
    - md.data.hawkeye.model
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
