micronaut:
  application:
    name: mdDataHawkeye
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
---
jpa:
  default:
    packages-to-scan:
    - md.data.hawkeye.model
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
